# the database image
db:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: ittybitty
    POSTGRES_PASSWORD: password
  volumes_from:
    - dbdata

# for persistance of database data
dbdata:
  image: postgres
  volumes:
    - /var/lib/postgres
  command: "true"

# the main image, this is the application
web:
  build: "."
  environment:
    MIX_ENV: "dev"
  ports:
    - "4000:4000"
  links:
    - "db:db"
    - "redis:redis"

redis:
  image: redis
  ports:
    - "6379"
